export const SERVICE_GROUPS = [
  { id: 'base', label: '基础服务', ids: ['basic_manicure_service'] as const, quantity: false },
  {
    id: 'removal',
    label: '卸甲',
    ids: ['removal_basic_gel', 'removal_extension', 'removal_with_rhinestone'] as const,
    quantity: false,
  },
  {
    id: 'extension',
    label: '建构/延长',
    ids: ['nail_tip_full_cover', 'nail_tip_half_cover', 'nail_tip_shallow_cover', 'builder_gel'] as const,
    quantity: false,
  },
  {
    id: 'color',
    label: '颜色效果',
    ids: [
      'color_split',
      'solid_color',
      'gradient',
      'aura_blush',
      'ink_wash',
      'jelly_translucent',
      'cat_eye',
      'glitter',
      'matte_top',
      'magnetic_special_effect',
    ] as const,
    quantity: true,
  },
  {
    id: 'art',
    label: '艺术效果',
    ids: [
      'french_tip_basic',
      'french_tip_special',
      'hand_paint_simple',
      'hand_paint_medium',
      'hand_paint_complex',
      'line_art',
      'pattern_art',
      '3d_art',
    ] as const,
    quantity: true,
  },
  {
    id: 'deco',
    label: '装饰效果',
    ids: [
      'sticker',
      'rhinestone_small',
      'rhinestone_large',
      'rhinestone_heavy',
      'pearl',
      'metal_charm',
      'bow_charm',
      'chain_charm',
      'shell_piece',
      'foil_piece',
      'chrome_powder',
      'aurora_powder',
      'pearl_powder',
    ] as const,
    quantity: true,
  },
] as const;

export type ServiceGroupId = (typeof SERVICE_GROUPS)[number]['id'];
